// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Helper to check if a string is a valid URL
const isValidUrl = (url: string): boolean => {
  try {
    const urlObj = new URL(url);
    return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
  } catch {
    return false;
  }
};

// Check if environment variables are configured
const isConfigured = SUPABASE_URL && 
                     SUPABASE_PUBLISHABLE_KEY && 
                     SUPABASE_URL !== 'your_supabase_project_url_here' && 
                     SUPABASE_PUBLISHABLE_KEY !== 'your_supabase_anon_key_here' &&
                     SUPABASE_URL !== 'https://placeholder.supabase.co' && 
                     SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key' &&
                     isValidUrl(SUPABASE_URL) &&
                     SUPABASE_URL.includes('supabase.co');

// Warn if not configured but don't crash the app
if (!isConfigured) {
  console.warn('⚠️ Supabase environment variables are missing or invalid.');
  console.warn('Please create a .env file in the project root with:');
  console.warn('VITE_SUPABASE_URL=your_supabase_project_url');
  console.warn('VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key');
  console.warn('The app will run but authentication features will not work.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a stub client for when Supabase is not configured
const createStubClient = (): SupabaseClient<Database> => {
  // Use a valid Supabase URL format that will pass validation
  // This won't actually work but won't crash the app
  try {
    return createClient<Database>(
      'https://00000000000000000000.supabase.co',
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IjAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjAwMDAwMDAwLCJleHAiOjE2MDAwMDAwMDB9.stub',
      {
        auth: {
          storage: {
            getItem: () => null,
            setItem: () => {},
            removeItem: () => {},
          },
          persistSession: false,
          autoRefreshToken: false,
          detectSessionInUrl: false,
        },
      }
    );
  } catch (error) {
    // If even this fails, we need to handle it differently
    console.error('Failed to create Supabase stub client:', error);
    // Return a minimal client - this should not happen but just in case
    return createClient<Database>(
      'https://placeholder.supabase.co',
      'placeholder-key',
      {
        auth: {
          storage: localStorage,
          persistSession: false,
          autoRefreshToken: false,
          detectSessionInUrl: false,
        },
      }
    );
  }
};

// Only create real client if configured, otherwise use stub
let supabaseInstance: SupabaseClient<Database>;

try {
  if (isConfigured) {
    // Create real Supabase client with actual credentials
    supabaseInstance = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: true,
        },
        global: {
          headers: {
            'x-client-info': 'sahaara-gyaan',
          },
        },
      }
    );
  } else {
    // Create stub client that won't crash but won't work
    supabaseInstance = createStubClient();
  }
} catch (error) {
  // If client creation fails for any reason, log and create stub
  console.error('Error creating Supabase client:', error);
  console.warn('Creating fallback stub client. Authentication features will not work.');
  try {
    supabaseInstance = createStubClient();
  } catch (stubError) {
    // Last resort - this should never happen, but if it does, we need a client
    console.error('Critical: Failed to create even stub client:', stubError);
    // Create with minimal config that should always work
    supabaseInstance = createClient<Database>(
      'https://00000000000000000000.supabase.co',
      'stub',
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
  }
}

export const supabase = supabaseInstance;

// Export configuration status
export const isSupabaseConfigured = isConfigured;

// Test connection on initialization
export const testSupabaseConnection = async (): Promise<{ connected: boolean; error?: string }> => {
  try {
    const { error } = await supabase.auth.getSession();
    if (error && !error.message.includes('session')) {
      return { connected: false, error: error.message };
    }
    return { connected: true };
  } catch (error: any) {
    return { 
      connected: false, 
      error: error?.message || 'Failed to connect to Supabase. Please check your internet connection and Supabase configuration.' 
    };
  }
};